trigger:
- master

pool: 
  name: Dev
  demands: agent.name -equals dev-build

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

resources:
  pipelines:
  - pipeline: Dev-Build
    source: Dev-Build
    trigger: true

steps:
- bash: echo "app-ci runs after security-lib-ci completes"
