# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool: 
  name: Dev
  demands: agent.name -equals dev-build

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  azureSubscription: 'Visual Studio Professional Subscription(77d14826-ec58-446e-aa89-f113654340aa)'
  appServiceName: ''

stages:
- stage: 'Build'
  displayName: 'Build Web Application'
  jobs:
  - job: 'Build'
    displayName: 'Building Web Application'
    steps:
      - task: UseDotNet@2
        inputs:
          packageType: 'sdk'
          version: '8.x'
          
      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
          projects: 'TaskPilot.Web/*.csproj'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: 'TaskPilot.Web/*.csproj'
          arguments: '--configuration $(buildConbfiguration)'

      - task: NuGetToolInstaller@1

      - task: NuGetCommand@2
        inputs:
          restoreSolution: '$(solution)'

- stage: 'Test'
  displayName: 'Testing Web Application'
  dependsOn: 'Build'
  condition: succeeded()
  jobs: 
  - job: 'Test'
    displayName: 'Running Unit Test'
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: 'TaskPilot.Tests/*.csproj'